[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true

[window.padding]
x = 10
y = 10

[font]
size = 12.5

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[general]
live_config_reload = true
